apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: devdenise/financeplatform-backend:latest # Replace with your image tag
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3001"
            - name: DATABASE_URL
              value: postgresql://dev:dev123@postgres:5432/financeplatform
            - name: REDIS_URL
              value: redis://redis:6379
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: jwt-secret
            - name: JWT_EXPIRES_IN
              value: 7d
            - name: CORS_ORIGIN
              value: http://localhost:3000
            - name: API_BASE_URL
              value: http://localhost:3001
            - name: PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK
              value: "1"
            - name: PRISMA_SCHEMA_PATH
              value: /app/prisma/schema.prisma
          # REMOVED: volumeMounts section that was mounting PVC to /app
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 30
      # REMOVED: volumes section that defined the PVC mount
