apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
   namespace: financeplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: devdenise/financeplatform-frontend:latest # Replace with your built image tag
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: development
            - name: NEXT_PUBLIC_API_URL
              value: /api/
            - name: NEXT_PUBLIC_APP_URL
              value: http://localhost:3000
            - name: NEXTAUTH_URL
              value: http://localhost:8080
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: nextauth-secret
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-oauth
                  key: client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-oauth
                  key: client-secret
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
