apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: financeplatform
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Access pgAdmin at localhost:30080 on Minikube

